name: colrvia
description: "Colrvia helps you discover your perfect color palette with a delightful, personalized interview experience, transforming your vision into vibrant design stories."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  supabase_flutter: '>=1.10.0'
  go_router: ^16.0.0
  shared_preferences: ^2.0.0
  image_picker: '>=1.1.2'
  permission_handler: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
